### ISSUE TITLE
"pip install pyart" fails on Windows 10 with Python 3.7.1

### ISSUE THREAD

**Issue by jtomshine** [blackwithwhite666/pyart#2]
[please disregard this issue, it was created in error]

**Comment by jtomshine** [comment]
Z:\code\wx_display>pip install pyart --no-cache-dir
Collecting pyart
  Downloading https://files.pythonhosted.org/packages/bd/88/813ba6b870578e337b33b8954a4ec2ed87900934007ec2a7d2338935b316/pyart-0.2.3.tar.gz (47kB)
     |████████████████████████████████| 51kB 1.1MB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\python\python37-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jshine\\AppData\\Local\\Temp\\pip-install-le8imzj_\\pyart\\setup.py'"'"'; __file__='"'"'C:\\Users\\jshine\\AppData\\Local\\Temp\\pip-install-le8imzj_\\pyart\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\jshine\AppData\Local\Temp\pip-install-le8imzj_\pyart\pip-egg-info'
         cwd: C:\Users\jshine\AppData\Local\Temp\pip-install-le8imzj_\pyart\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jshine\AppData\Local\Temp\pip-install-le8imzj_\pyart\setup.py", line 139, in <module>
        kwargs['sources'] = prepare_sources(kwargs['sources'])
      File "C:\Users\jshine\AppData\Local\Temp\pip-install-le8imzj_\pyart\setup.py", line 121, in prepare_sources
        return [to_string(source) for source in sources]
      File "C:\Users\jshine\AppData\Local\Temp\pip-install-le8imzj_\pyart\setup.py", line 121, in <listcomp>
        return [to_string(source) for source in sources]
      File "C:\Users\jshine\AppData\Local\Temp\pip-install-le8imzj_\pyart\setup.py", line 118, in to_string
        if isinstance(s, unicode):
    NameError: name 'unicode' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by jtomshine** [comment]
> Z:\code\wx_display>pip install pyart --no-cache-dir
Collecting pyart
  Downloading https://files.pythonhosted.org/packages/bd/88/813ba6b870578e337b33b8954a4ec2ed87900934007ec2a7d2338935b316/pyart-0.2.3.tar.gz (47kB)
     |████████████████████████████████| 51kB 1.1MB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\python\python37-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jshine\\AppData\\Local\\Temp\\pip-install-le8imzj_\\pyart\\setup.py'"'"'; __file__='"'"'C:\\Users\\jshine\\AppData\\Local\\Temp\\pip-install-le8imzj_\\pyart\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\jshine\AppData\Local\Temp\pip-install-le8imzj_\pyart\pip-egg-info'
         cwd: C:\Users\jshine\AppData\Local\Temp\pip-install-le8imzj_\pyart\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jshine\AppData\Local\Temp\pip-install-le8imzj_\pyart\setup.py", line 139, in <module>
        kwargs['sources'] = prepare_sources(kwargs['sources'])
      File "C:\Users\jshine\AppData\Local\Temp\pip-install-le8imzj_\pyart\setup.py", line 121, in prepare_sources
        return [to_string(source) for source in sources]
      File "C:\Users\jshine\AppData\Local\Temp\pip-install-le8imzj_\pyart\setup.py", line 121, in <listcomp>
        return [to_string(source) for source in sources]
      File "C:\Users\jshine\AppData\Local\Temp\pip-install-le8imzj_\pyart\setup.py", line 118, in to_string
        if isinstance(s, unicode):
    NameError: name 'unicode' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by jtomshine** [comment]
<img width="939" alt="Untitled" src="https://user-images.githubusercontent.com/5215989/70651381-4c1c4200-1c16-11ea-9752-822eaaa43647.png">
